service: lambda-bot
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  stage: pro
  region: ap-southeast-1
  environment:
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}
    SERVICE_NAME: ${self:service}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:ap-southeast-1:646978820291:table/Links'

package:
  exclude:
    - ./**
  include:
    - ./bin/**
    - ./public/**

functions:
  kyler-bot:
    handler: bin/kyler-bot
    events:
      - http:
          path: kyler-bot
          method: post

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: 'bots.kylerwong.dev'
    basePath: 'telegram'
    stage: ${self:provider.stage}
    createRoute53Record: false
    endpointType: 'regional'
