service: golang-lambda
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  stage: pro
  region: ap-southeast-1
  environment:
    SERVICE_NAME: ${self:service}

  # Enable the following if hooking up DynamoDB.

  # iamRoleStatements:
  #   - Effect: 'Allow'
  #     Action:
  #       - dynamodb:Query
  #       - dynamodb:Scan
  #       - dynamodb:GetItem
  #       - dynamodb:PutItem
  #       - dynamodb:UpdateItem
  #       - dynamodb:DeleteItem
  #     Resource: 'arn:aws:dynamodb:ap-southeast-1:646978820291:table/Hello'

package:
  exclude:
    - ./**
  include:
    - ./bin/**
    - ./public/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: 'hello.kylerwong.dev'
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: false
    endpointType: 'regional'
